language: csharp 
dist: trusty
mono: none
dotnet: 2.1
branches:  
  only:  
    - master
script:  
  - dotnet restore 
  - dotnet build ./ExtensionsCoreUtils/
  - dotnet test ./ExtensionsCoreUtils.Tests/